-- CreateEnum
CREATE TYPE "Color" AS ENUM ('CYAN', 'BLUE', 'PURPLE', 'GREEN', 'YELLOW', 'RED', 'PINK');

-- CreateEnum
CREATE TYPE "Icons" AS ENUM ('CALENDAR', 'AWARD', 'CHECK_CIRCLE', 'QUESTION_MARK_CIRCLE', 'MESSAGE_SQUARE', 'MAIL_CHECK', 'ALARM_CLOCK', 'TRASH', 'EYE', 'EYE_CLOSED', 'FLAG', 'MIC', 'X_CIRCLE');

-- AlterTable
ALTER TABLE "Column" ADD COLUMN     "color" "Color" NOT NULL DEFAULT 'CYAN',
ADD COLUMN     "icon" "Icons" NOT NULL DEFAULT 'CALENDAR';
